### ISSUE TITLE
Fix font size for retina (high resolution) screens

### ISSUE THREAD

**Issue by wigging** [scipy-lectures/scipy-lecture-notes#346]
The font on the http://www.scipy-lectures.org website is huge. I'm not sure if this is an issue for everyone, but on my MacBook Pro I have to zoom out on the webpage to properly view the content. Please update the site with a more reasonable font size for high resolution screens.

![screenshot](https://user-images.githubusercontent.com/6828967/31313953-a07f3bcc-abc0-11e7-930b-491cb99ab030.png)

**Comment by GaelVaroquaux** [comment]
OK, so it seems that we have a CSS bug with retina displays.

Can take a screenshot of the CSS rules that are active for the text?

**Comment by wigging** [comment]
Can you explain how I should take a screenshot of the CSS rules with the Safari web browser?

**Comment by rougier** [comment]
You can use the "inspect element". I got the same output, here is the result

<img width="1680" alt="untitled" src="https://user-images.githubusercontent.com/327203/31356283-c6e59008-ad3d-11e7-83f5-0b6694361722.png">

**Comment by wigging** [comment]
Changing the body font-size to 100% looks much better.

```css
@media	only screen and (-webkit-min-device-pixel-ratio: 2),
	only screen and (-o-min-device-pixel-ratio: 18/10),
	only screen and (min-resolution: 170dpi)
{
  /* Even higher DPI devices */
  body {
    font-size: 100%;
  }
}
```

**Comment by pdebuyl** [comment]
Any way to "emulate" this display for non-retina computers?

**Comment by pdebuyl** [comment]
See #374 and fixed by #375

**Comment by wigging** [comment]
@pdebuyl This issue is still **not** fixed. The font size is extremely large on high-resolution displays.

**Comment by pdebuyl** [comment]
Hi @wigging we currently have a rather slow publication process. The fixes only go live after a release

Does it work for you at http://pdebuyl.be/tmp/sln-retina/

If yes, I'll push for a release soon.

**Comment by wigging** [comment]
@pdebuyl Yes, the tmp site looks better. The font size is still large but not as bad as the original version of the site.

**Comment by pdebuyl** [comment]
Thank you for the feedback.
